"""changed ad model

Revision ID: e5f03f73889f
Revises: 5e678d93c2e2
Create Date: 2023-09-24 14:35:04.994953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f03f73889f'
down_revision = '5e678d93c2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_constraint('ads_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ads_company_id_fkey', 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###
